name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Set up Gradle (no wrapper)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Download EfficientDet Lite0 model
        run: |
          ASSETS=app/src/main/assets
          mkdir -p "$ASSETS"
          curl -L "https://storage.googleapis.com/tfhub-lite-models/tensorflow/lite-model/efficientdet/lite0/detection/metadata/1.tflite" -o "$ASSETS/efficientdet_lite0.tflite"

      - name: Build app (Debug)
        run: gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
